In [ ]:
# Supervised Machine Learning-Regression & Classification
# Regression -- Multiple Linear Regression

# Multiple Linear Regression is a fundamental statistical technique used to model
# the relationship between one dependent variable and multiple independent
# variables. It is an extension of simple linear regression, which models the relationship
# between a dependent variable and one or more independent variable.

# MLR
# Pickle
# Github- folder(repositories/repo)
# -Python-all your python projects
# -Data Sc - EDA Data Cleaning
# -ML - All ML Projects
# -Datasets
# Visual Studio Code [streamlit]-make python application live

# Step:
# Data Gathering
# EDA
# Algorithm

In [ ]:
# Third Project : Predicting Profit Based On Multiple Independent Variable

# Load The Dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/yash240990/Python/master/Startups_Data.csv')
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [ ]:
# Select Independent and Dependent Variable
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [ ]:
x = ['R&D Spend', 'Administration', 'Marketing Spend', 'State']   # create list (Independent Variable)
x = data[x].values  # to only generate values, not with list and column
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 294919.57, 'Florida'],
       [86419.7, 153514.11, 0.0, 'New York'],
       [76253.86, 113867.3, 298664.47, 'California'],
       [78389.47, 153773.43, 299737.29, 'New York'],
       [73994.56, 122782.75, 303319.26, 'Florida'],
       [67532.53, 105751.03, 304768.73, 'Florida'],
       [77044.01, 99281.34, 140574.81, 'New York'],
       [64664.71, 139553.16, 137962.62, 'California'],
       [75328.87, 144135.98, 134050.07, 'Florida'],
       [72107.6, 127864.55, 353183.81, 'New York'],
       [66051.52, 182645.56, 118148.2, 'Florida'],
       [65605.48, 153032.06, 107138.38, 'New York'],
       [61994.48, 115641.28, 91131.24, 'Florida'],
       [61136.38, 152701.92, 88218.23, 'New York'],
       [63408.86, 129219.61, 46085.25, 'California'],
       [55493.95, 103057.49, 214634.81, 'Florida'],
       [46426.07, 157693.92, 210797.67, 'California'],
       [46014.02, 85047.44, 205517.64, 'New York'],
       [28663.76, 127056.21, 201126.82, 'Florida'],
       [44069.95, 51283.14, 197029.42, 'California'],
       [20229.59, 65947.93, 185265.1, 'New York'],
       [38558.51, 82982.09, 174999.3, 'California'],
       [28754.33, 118546.05, 172795.67, 'California'],
       [27892.92, 84710.77, 164470.71, 'Florida'],
       [23640.93, 96189.63, 148001.11, 'California'],
       [15505.73, 127382.3, 35534.17, 'New York'],
       [22177.74, 154806.14, 28334.72, 'California'],
       [1000.23, 124153.04, 1903.93, 'New York'],
       [1315.46, 115816.21, 297114.46, 'Florida'],
       [0.0, 135426.92, 0.0, 'California'],
       [542.05, 51743.15, 0.0, 'New York'],
       [0.0, 116983.8, 45173.06, 'California']], dtype=object)

In [ ]:
x.shape # Independent Variable already in 2D, does no need to reshape

(50, 4)

In [ ]:
y = data.Profit.values  # dependent Variable
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [ ]:
# OneHotEncoding
# One-Hot Encoding is a data preprocessing technique used to convert
# categorical (text) data into numerical form so that machine learning models can
# understand it.


from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(
    transformers = [('OneHot',OneHotEncoder(),[3])],  # List of (name,transformer,columns), List of tuples = [()]
    remainder = 'passthrough' # please do not remove non specified columns
)

x = transformer.fit_transform(x)
x = x.astype('int')

In [ ]:
x

# california  florida   newYork   r_d     admin     market
#     0,        0,          1,   165349,  136897,   471784
#     1,        0,          0,   162597,  151377,   443898

# newYork --> 0 0 1
# california --> 1 0 0
# florida --> 0 1 0

array([[     0,      0,      1, 165349, 136897, 471784],
       [     1,      0,      0, 162597, 151377, 443898],
       [     0,      1,      0, 153441, 101145, 407934],
       [     0,      0,      1, 144372, 118671, 383199],
       [     0,      1,      0, 142107,  91391, 366168],
       [     0,      0,      1, 131876,  99814, 362861],
       [     1,      0,      0, 134615, 147198, 127716],
       [     0,      1,      0, 130298, 145530, 323876],
       [     0,      0,      1, 120542, 148718, 311613],
       [     1,      0,      0, 123334, 108679, 304981],
       [     0,      1,      0, 101913, 110594, 229160],
       [     1,      0,      0, 100671,  91790, 249744],
       [     0,      1,      0,  93863, 127320, 249839],
       [     1,      0,      0,  91992, 135495, 252664],
       [     0,      1,      0, 119943, 156547, 256512],
       [     0,      0,      1, 114523, 122616, 261776],
       [     1,      0,      0,  78013, 121597, 264346],
       [     0,      0,      1,  94657, 145077, 282574],
       [     0,      1,      0,  91749, 114175, 294919],
       [     0,      0,      1,  86419, 153514,      0],
       [     1,      0,      0,  76253, 113867, 298664],
       [     0,      0,      1,  78389, 153773, 299737],
       [     0,      1,      0,  73994, 122782, 303319],
       [     0,      1,      0,  67532, 105751, 304768],
       [     0,      0,      1,  77044,  99281, 140574],
       [     1,      0,      0,  64664, 139553, 137962],
       [     0,      1,      0,  75328, 144135, 134050],
       [     0,      0,      1,  72107, 127864, 353183],
       [     0,      1,      0,  66051, 182645, 118148],
       [     0,      0,      1,  65605, 153032, 107138],
       [     0,      1,      0,  61994, 115641,  91131],
       [     0,      0,      1,  61136, 152701,  88218],
       [     1,      0,      0,  63408, 129219,  46085],
       [     0,      1,      0,  55493, 103057, 214634],
       [     1,      0,      0,  46426, 157693, 210797],
       [     0,      0,      1,  46014,  85047, 205517],
       [     0,      1,      0,  28663, 127056, 201126],
       [     1,      0,      0,  44069,  51283, 197029],
       [     0,      0,      1,  20229,  65947, 185265],
       [     1,      0,      0,  38558,  82982, 174999],
       [     1,      0,      0,  28754, 118546, 172795],
       [     0,      1,      0,  27892,  84710, 164470],
       [     1,      0,      0,  23640,  96189, 148001],
       [     0,      0,      1,  15505, 127382,  35534],
       [     1,      0,      0,  22177, 154806,  28334],
       [     0,      0,      1,   1000, 124153,   1903],
       [     0,      1,      0,   1315, 115816, 297114],
       [     1,      0,      0,      0, 135426,      0],
       [     0,      0,      1,    542,  51743,      0],
       [     1,      0,      0,      0, 116983,  45173]])

In [ ]:
# train test split
# in machine learning (ML), we teach computers to make predictions
# or decisions based on data.
# To make sure our model learns properly and doesn’t just memorize,
# we divide our data into two parts:
# 1. Training set – used to teach the model
# 2. Testing set – used to check if the model really learned or just memorized

# random_state do?
# random_state acts like a seed — it makes sure the random process happens
# the same way every time you run the code. That means if you (or someone else)
# run your code again, you’ll get exactly the same split.

# Why number 42?
# There’s nothing special about 42 mathematically — it’s just
# a popular “inside joke” among programmers, from a famous
# sci-fi book “The Hitchhiker’s Guide to the Galaxy”,
# where 42 is “the answer to life, the universe, and everything.”

In [ ]:
# train test split-make sure the ML is learning NOT memorizing
# 0.2 means 20% of the data will be using for Testing
# remaining 0.8 means 80% of the data will be using for Training
# maximum for Testing is 0.35, for Training to be higher

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
print('Original Shape')
print(x.shape)
print(y.shape)
print('After Splitting')
print(x_train.shape)    # 40 records use for training, 10 records will be used for training
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

Original Shape
(50, 6)
(50,)
After Splitting
(40, 6)
(10, 6)
(40,)
(10,)

In [ ]:
import sklearn.linear_model as lm
mlr = lm.LinearRegression()

mlr.fit(x_train,y_train)

LinearRegression()

In [ ]:
pred_values = mlr.predict(x_test) # testing the ml(x_test)
print(pred_values)

[126362.93252168  84608.52579885  99677.45007315  46357.54709785
 128750.69322702  50912.79650842 109741.00850973 100643.01925188
  97598.94761156 113097.03975182]

In [ ]:
from sklearn.metrics import r2_score
score = r2_score(y_test,pred_values)  # comparing the IV with dependent variable(y_test)
print(f'Regression Score : {score}')

Regression Score : 0.8987245306209427

In [ ]:
# Final Predictions
california = int(input('Is startup in california. Enter 1 is Yes and Else 0 :'))
florida = int(input('Is startup in florida. Enter 1 is Yes and Else 0 :'))
newYork = int(input('Is startup in newYork. Enter 1 is Yes and Else 0 :'))
r_d = int(input('Enter Research and Development Spend :'))
admin = int(input('Enter Administration Spend :'))
market = int(input('Enter Marketing Spend :'))

# convert user input into a dictionary
user_data = {'california':california , 'florida':florida , 'newYork':newYork ,
             'r_d':r_d , 'admin':admin , 'market':market}

# convert this dictionary into DataFrame
user_input = pd.DataFrame(user_data,index=[0])
user_input

Is startup in california. Enter 1 is Yes and Else 0 :1
Is startup in florida. Enter 1 is Yes and Else 0 :0
Is startup in newYork. Enter 1 is Yes and Else 0 :0
Enter Research and Development Spend :162597
Enter Administration Spend :151377
Enter Marketing Spend :443898

   california  florida  newYork     r_d   admin  market
0           1        0        0  162597  151377  443898

In [ ]:
user_input.values

array([[     1,      0,      0, 162597, 151377, 443898]])

In [ ]:
predict_profit = mlr.predict(user_input.values)
print(f'Predicted Profit Will Be {int(predict_profit[0])}')

Predicted Profit Will Be 187861